name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    name: Deploy Release
    permissions:
      contents: write
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - target: "x86_64-unknown-linux-gnu"
            os: "ubuntu-latest"
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.target }}
      - name: Build and deploy artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG=${GITHUB_REF#*/tags/}
          mkdir dist
          cd target/${{ matrix.target }}/release
          tar czf ../../../dist/circleci-junit-fix-${TAG}-${{ matrix.target }}.tar.gz circleci-junit-fix
        shell: bash
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
